services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  jupyter-notebook:
    image: jupyter/datascience-notebook:latest
    ports:
      - 10000:8888
    volumes:
      - ./notebook:/home/jovyan/work
