services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  jupyter-notebook:
    image: jupyter/datascience-notebook:latest
    ports:
      - 10000:8888
    volumes:
      - jupyter_notebook_data:/home/jovyan/work
volumes:
  mongodb_data:
  jupyter_notebook_data:
